config/routes.rb
Retrospective::Application.routes.draw do

  resources :projects do
    resources :iterations
  end

  root :to => "projects#index"

end

app/models/iteration.rb
class Iteration < ActiveRecord::Base
  belongs_to :project

  validates_presence_of :project_id
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :iterations

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/iterations_controller.rb
class IterationsController < ApplicationController
  respond_to :html

  # def index
  #  respond_with(@iterations = Iteration.all)
  # end

  def show
    respond_with(@iteration = Iteration.find(params[:id]))
  end

  def new
    @project = Project.find(params[:project_id])
    respond_with(@iteration = Iteration.new)
  end

  def edit
    respond_with(@iteration = Iteration.find(params[:id]))
  end

  def create
    @iteration = Iteration.create(params[:iteration])
    flash[:notice] = 'Iteration was successfully created.'
    respond_with(Project.find(params[:project_id]), @iteration)
  end

  def update
    @iteration = Iteration.find(params[:id])
    flash[:notice] = 'Iteration was successfully updated.' if @iteration.update_attributes(params[:iteration])
    respond_with(Project.find(params[:project_id]), @iteration)
  end

  def destroy
    @iteration = Iteration.find(params[:id])
    project = @iteration.project
    @iteration.destroy
    redirect_to project_path(project)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html

  def index
    respond_with(@projects = Project.all)
  end

  def show
    @project = Project.find(params[:id])
    respond_with(@project, @iterations = @project.iterations)
  end

  def new
    respond_with(@project = Project.new)
  end

  def edit
    respond_with(@project = Project.find(params[:id]))
  end

  def create
    @project = Project.create(params[:project])
    flash[:notice] = 'Project was successfully created.'

    respond_with(@project, :location => @project)
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(params[:project])
    flash[:notice] = 'Project was successfully updated.'
    respond_with(@project, :location => @project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_with(@project, :head => :ok)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/iterations_helper.rb
module IterationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/iterations/_form.html.erb
<%= form_for(@iteration, :url => project_iterations_path) do |f| %>
  <% if @iteration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

      <ul>
      <% @iteration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.date_select :end %>
  </div>
  <div class="actions">
    <%= f.hidden_field :project_id, :value => @project.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/iterations/edit.html.erb
<h1>Editing iteration</h1>

<%= render 'form' %>

<%= link_to 'Show', @iteration %> |
<%= link_to 'Back', project_iterations_path %>

app/views/iterations/new.html.erb
<h1>New iteration</h1>

<%= render 'form' %>

<%= link_to 'Back', project_iterations_path %>

app/views/iterations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @iteration.name %>
</p>

<p>
  <b>Start:</b>
  <%= @iteration.start %>
</p>

<p>
  <b>End:</b>
  <%= @iteration.end %>
</p>

<%= link_to 'Edit', edit_project_iteration_path(@iteration) %> |
<%= link_to 'Back', project_path(@iteration.project) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Retrospective</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

<h1>Listing iterations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start</th>
    <th>End</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @iterations.each do |iteration| %>
  <tr>
    <td><%= iteration.name %></td>
    <td><%= iteration.start %></td>
    <td><%= iteration.end %></td>
    <td><%= link_to 'Show', project_iteration_path(@project, iteration) %></td>
    <td><%= link_to 'Edit', edit_project_iteration_path(@project, iteration) %></td>
    <td><%= link_to 'Destroy', project_iteration_path(@project, iteration), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Iteration', new_project_iteration_path(@project) %>